version: '3'
services:

  web:
    image: node:20
    ports: [ '5173:5173' ]
    environment:
      VITE_CLIENT_ID: 'uuid'
      VITE_AUTHORITY: 'https://login.microsoft.com/uuid'
    working_dir: '/app'
    volumes: [ '.:/app:z' ]
    command: [ 'npm', 'run', 'dev' ]
